version: 2

project_name: atun

builds:
  - id: build-glibc
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'github.com/automationd/atun/internal/version.Version={{.Version}}' -X 'github.com/automationd/atun/internal/version.GitCommit={{.Env.SHORT_SHA}}'

  - id: build-musl
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - 386
    tags:
      - musl
    ldflags:
      - -s -w -X 'github.com/automationd/atun/internal/version.Version={{.Version}}' -X 'github.com/automationd/atun/internal/version.GitCommit={{.Env.SHORT_SHA}}'

archives:
  - id: archive-glibc
    ids:
      - build-glibc
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

  - id: archive-musl
    ids:
      - build-musl
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-musl"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: AutomationD
    name: atun
  draft: true
  replace_existing_draft: true
  make_latest: false

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"

brews:
  - name: atun-dev
    ids:
      - archive-glibc
    repository:
      owner: AutomationD
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    url_template: "https://github.com/AutomationD/atun/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Dmitry Kireev
      email: dmitry@atd.sh
    homepage: "https://github.com/AutomationD/atun"
    description: "atun.io is a simple SSM/SSH tunnel manager"
    license: "Apache 2.0"
    conflicts:
      - atun
      - atun@{{ .Version }}
    test: |
      system "#{bin}/atun version"
    install: |
      bin.install "atun"

  - name: atun-dev@{{ .Version }}
    ids:
      - archive-glibc
    repository:
      owner: AutomationD
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    url_template: "https://github.com/AutomationD/atun/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Dmitry Kireev
      email: dmitry@atd.sh
    homepage: "https://github.com/AutomationD/atun"
    description: "atun.io is a simple SSM/SSH tunnel manager"
    license: "Apache 2.0"
    conflicts:
      - atun
      - atun@{{ .Version }}
    test: |
      system "#{bin}/atun version"
    install: |
      bin.install "atun"

scoops:
  - name: atun-dev
    url_template: "https://github.com/AutomationD/atun/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Dmitry Kireev
      email: dmitry@atd.sh
    commit_msg_template: "{{ .ProjectName }} {{ .Tag }} update"
    description: "Atun is a simple SSM/SSH tunnel manager"
    license: Apache License 2.0
    skip_upload: false
    depends: ["python"]
    repository:
      owner: AutomationD
      name: scoop-bucket
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

  - name: atun-dev@{{ .Version }}
    url_template: "https://github.com/AutomationD/atun/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Dmitry Kireev
      email: dmitry@atd.sh
    commit_msg_template: "{{ .ProjectName }} {{ .Tag }} update"
    description: "Atun is a simple SSM/SSH tunnel manager"
    license: Apache License 2.0
    skip_upload: false
    depends: ["python"]
    repository:
      owner: AutomationD
      name: scoop-bucket
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

nfpms:
  - id: nfpm-musl
    package_name: atun
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}-musl"
    ids:
      - build-musl
    formats:
      - apk
    vendor: Dmitry Kireev
    homepage: https://atun.io
    maintainer: Dmitry Kireev <dmitry@atd.sh>
    description: atun.io is a simple SSM/SSH tunnel manager
    license: Apache 2.0
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/atun/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/atun/README.md

  - id: nfpm-glibc
    ids:
      - build-glibc
    package_name: atun
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    vendor: AutomationD
    homepage: https://github.com/AutomationD/atun
    maintainer: Dmitry Kireev <dmitry@atd.sh>
    description: atun.io is a simple SSM/SSH tunnel manager
    license: Apache 2.0
    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    # by specifying `packages` id here goreleaser will only use this publisher
    # with artifacts identified by this id
    ids:
      - nfpm-musl
    dir: "{{ dir .ArtifactPath }}"
    cmd: |
      fury push {{ .ArtifactName }} --public --account automationd --api-token {{ .Env.FURY_TOKEN }}
#    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/automationd/

