name: Release Build
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  release:
    types:
      - created

  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    name: Build and Release with GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.8 # Until https://github.com/golang/go/issues/73617 is fixed

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean -f .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          RELEASE_VERSION: "${{ env.RELEASE_VERSION }}"
          FURY_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
          GIT_SHA: ${{ env.SHORT_SHA }}
          GITHUB_ACTOR: ${{ github.actor }}


      - name: Generate Banner
        uses: DimmKirr/action-brutalease@v1
        with:
          version: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          repo_url: ${{ github.repository }}
          output: release-banner.png
          project_name: Atun
          project_description: Tunnels Simplified
          theme: |
            bgOne: '#009DFF'
            bgTwo: '#ffffff'
            bgThree: '#f5f5f5'
            accentOne: '#ffac00'
            accentTwo: '#FFE3D3'
            accentThree: '#888'
            text: '#000000'
            fontFamily: 'Roboto'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-banner
          path: release-banner.png

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: release-banner.png
          tag_name: ${{ github.event.release.tag_name }}

      - name: Update release description with image
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          IMAGE_URL: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/release-banner.png
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get current release body
          RELEASE_BODY=$(gh release view "$RELEASE_TAG" --json body -q .body)

          # Create a temporary file with the new release body
          echo -e "![Release Banner]($IMAGE_URL)\n\n$RELEASE_BODY" > new_body.md

          # Update the release with the new body
          gh release edit "$RELEASE_TAG" --notes-file new_body.md

      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "${{ env.RELEASE_VERSION }}" --draft=false --latest=false
